CREATE TABLE IF NOT EXISTS items (
    item_no VARCHAR(20) PRIMARY KEY,
    item_name VARCHAR(150),
    retail_price DECIMAL(18,2),
    uom VARCHAR(10),
    barcode VARCHAR(30),
    division_code VARCHAR(2),
    division_name VARCHAR(50),
    group_code VARCHAR(4),
    group_name VARCHAR(50),
    category_code VARCHAR(6),
    category_name VARCHAR(50),
    created_date DATE,
    is_synced_app_web BOOLEAN,
    purchase_channel VARCHAR(20),
    business_status VARCHAR(30),
    maker VARCHAR(30),
    carton_barcode VARCHAR(20),
    mission VARCHAR(30),
    pack_size INT,
    item_role VARCHAR(15),
    fc_price DECIMAL(18,2),
    block_status VARCHAR(10),
    declaration_type VARCHAR(15),
    lead_time_days INT,
    shelf_life_days INT,
    length_mm DECIMAL(10,2),
    width_mm DECIMAL(10,2),
    height_mm DECIMAL(10,2),
    cbm DECIMAL(18,8),
    vendor_name VARCHAR(100),
    sjs_catalog_flag VARCHAR(10),
    fc_catalog_flag VARCHAR(10),
    delivery_to VARCHAR(10),
    full_carton_flag VARCHAR(10),
    vendor_type VARCHAR(30),
    transfer_group VARCHAR(20),
    md_classification VARCHAR(30),
    vat_classification VARCHAR(50),
    dosage DECIMAL(18,6),
    catalog_level VARCHAR(10),
    image_file VARCHAR(100),
    old_barcode VARCHAR(30),
    sub_code VARCHAR(50),
    goods_status VARCHAR(30),
    min_stock_s INT,
    min_stock_m INT,
    min_stock_l INT,
    min_stock_current INT,
    pic_cu VARCHAR(50),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_items_barcode ON items(barcode);
